name: Update Wiki

on:
  push:
    branches:
      - master

jobs:
  update_wiki:
    runs-on: ubuntu-18.04
    steps:
      - name: change_config
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}"


